# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

from core import fields


class Migration(migrations.Migration):

    dependencies = [
        ('spbgti_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Семестр')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('rank', fields.RankField(blank=True, choices=[('1', 'к.т.н'), ('2', 'д.т.н.')], max_length=1, null=True, verbose_name='Ученая степень')),
                ('position', fields.PositionField(choices=[('1', 'профессор'), ('2', 'доцент'), ('3', 'старший преподаватель'), ('4', 'ассистент')], max_length=1, verbose_name='Должность')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbgti_core.Location'),
        ),
    ]
