# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 21:00
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160901_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=core.fields.PositionField(blank=True, choices=[('1', 'профессор'), ('2', 'доцент'), ('3', 'старший преподаватель'), ('4', 'ассистент')], max_length=1, null=True, verbose_name='Должность'),
        ),
    ]
