# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170211_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер группы'),
        ),
    ]
