# Generated by Django 2.2.4 on 2019-11-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170220_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ФИО'),
        ),
    ]
