# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 12:15
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('pair', core.fields.PairField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая')], default=1, max_length=1, verbose_name='Номер пары')),
                ('day', core.fields.DayOfTheWeekField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default=1, max_length=1, verbose_name='День недели')),
                ('parity', core.fields.ParityField(blank=True, choices=[('1', 'Четная'), ('2', 'Нечетная')], default=1, max_length=1, null=True, verbose_name='Четность')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2016', max_length=4, verbose_name='Год')),
                ('semester', models.CharField(default='1', max_length=1, verbose_name='Номер семестра')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Schedule'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='core.Teacher'),
        ),
    ]
