# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 22:39
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип пары'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='parity',
            field=core.fields.ParityField(choices=[('1', 'Четная'), ('2', 'Нечетная')], default=1, max_length=1, null=True, verbose_name='Четность'),
        ),
    ]
