# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

from spbgti_core import fields


class Migration(migrations.Migration):

    dependencies = [
        ('spbgti_core', '0002_auto_20160608_2358'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('pair', fields.PairField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая')], default=1, max_length=1, verbose_name='Номер пары')),
                ('day', fields.DayOfTheWeekField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default=1, max_length=1, verbose_name='День недели')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbgti_core.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='year',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbgti_core.Group'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbgti_core.Semester'),
        ),
        migrations.DeleteModel(
            name='ClassRecord',
        ),
        migrations.AddField(
            model_name='exercise',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Schedule'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbgti_core.Teacher'),
        ),
    ]
