# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160911_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название занятия'),
        ),
    ]
