# Generated by Django 2.2.4 on 2019-11-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170211_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Group'),
        ),
    ]
