# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=20, verbose_name='Временные рамки')),
                ('class_name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('place', models.CharField(max_length=20, verbose_name='Место проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='Номер группы')),
                ('year', models.DateField(default=django.utils.timezone.now, verbose_name='Год')),
                ('semester', models.IntegerField(verbose_name='Номер семестра')),
            ],
        ),
        migrations.AddField(
            model_name='classrecord',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
    ]
