# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecord',
            name='time_range',
        ),
        migrations.AddField(
            model_name='classrecord',
            name='day',
            field=models.IntegerField(default=0, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='pair',
            field=models.IntegerField(default=0, verbose_name='Номер пары'),
        ),
    ]
