# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 20:36
from __future__ import unicode_literals

from django.db import migrations
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160605_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='day',
            field=schedule.models.DayOfTheWeekField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default=1, max_length=1, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='pair',
            field=schedule.models.PairField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая'), ('6', 'Шестая'), ('7', 'Седьмая')], default=1, max_length=1, verbose_name='Номер пары'),
        ),
    ]
